from xbot import bot
from xbot.utils import x_cmd, sudo_cmd

x = True
@bot.on(x_cmd(pattern="raid"))
@bot.on(sudo_cmd(pattern="raid", allow_sudo=True))
async def fightbot(event):
       
        await event.delete()
        kek = event.chat_id
        await bot.send_message(kek, "Pehle main tereko chakna dega, fir daru pilayega, fir jab aap dimag se nahi L*nd se sochoge, tab bolega..")
        await bot.send_message(kek, "Pardhan mantri se number liya, parliament apne :__;baap ka hai...")
        await bot.send_message(kek, "It's better to let someone think you are an Idiot than to open your mouth and prove it.")
        await bot.send_message(kek, "Aaisi Londiya Chodiye, L*nd Ka Aapa Khoye, Auro Se Chudi Na Ho, Biwi Wo Hi Hoye")
        await bot.send_message(kek, "It's better to let someone think you are an Idiot than to open your mouth and prove it.")
        await bot.send_message(kek, "Pardhan mantri se number liya, parliament apne :__;baap ka hai...")
        await bot.send_message(kek, "Nachoo Bhosdike Nachoo")
        await bot.send_message(kek, "Talking to a liberal is like trying to explain social media to a 70 years old")
        await bot.send_message(kek, "CHAND PE HAI APUN LAWDE.")
        await bot.send_message(kek, "Pehle main tereko chakna dega, fir daru pilayega, fir jab aap dimag se nahi L*nd se sochoge, tab bolega..")
        await bot.send_message(kek, "Jinda toh jaat ke baal bhi hai")
        await bot.send_message(kek, "Pehle main tereko chakna dega, fir daru pilayega, fir jab aap dimag se nahi L*nd se sochoge, tab bolega..")
        await bot.send_message(kek, "Sab ko pta tu randi ka baccha hai")
        await bot.send_message(kek, "Cachaa Ooo bhosdi wale Chacha")
        await bot.send_message(kek, "Sab ko pta tu randi ka baccha hai")
        await bot.send_message(kek, "Maderchod- MOTHERFUCKER")
        await bot.send_message(kek, "Bhosadike-BORN FROM A ROTTEN PUSSY")
        await bot.send_message(kek, "Bhen chod-Sister fucker")
        await bot.send_message(kek, "Bhadhava- Pimp")
        await bot.send_message(kek, "Chodu- Fucker")
        await bot.send_message(kek, "Chutiya- Fucker, bastard")
        await bot.send_message(kek, "Gaand- ASS")
        await bot.send_message(kek, "Gaandu-Asshole")
        await bot.send_message(kek, "Gadha, Bakland- Idiot")
        await bot.send_message(kek, "Lauda, Lund- Penis, dick, cock")
        await bot.send_message(kek, "Hijra- Gay, Transsexual")
        await bot.send_message(kek, "Kuttiya- Bitch")
        await bot.send_message(kek, "Randi- HOOKER")
        await bot.send_message(kek, "Saala kutta- Bloody dog")
        await bot.send_message(kek, "Saali kutti- Bloody bitch")
        await bot.send_message(kek, "Tatti- Shit")
        await bot.send_message(kek, "Kamina")
        await bot.send_message(kek, "Chut ke pasine mein talay huye bhajiye- Snack fried in pussy sweat")
        await bot.send_message(kek, "Chut ke dhakkan- Pussy lid")
        await bot.send_message(kek, "Chut ke gulam")
        await bot.send_message(kek, "Chutiya ka bheja ghas khane gaya hai- idiot? brain has gone to eat grass")
        await bot.send_message(kek, "Choot marani ka- Pussy whipped")
        await bot.send_message(kek, "Choot ka baal")
        await bot.send_message(kek, "Chipkali ke jhaat ke baal")
        await bot.send_message(kek, "Chipkali ke jhaat ke paseene")
        await bot.send_message(kek, "Chipkali ke gaand ke pasine")
        await bot.send_message(kek, "Chipkali ke chut ke pasine")
        await bot.send_message(kek, "Chipkali ki bhigi chut")
        await bot.send_message(kek, "Chinaal ke gadde ke nipple ke baal ke joon")
        await bot.send_message(kek, "Chullu bhar muth mein doob mar")
        await bot.send_message(kek, "Cuntmama Chhed")
        await bot.send_message(kek, "Apni gaand mein muthi daal")
        await bot.send_message(kek, "Apni lund choos")
        await bot.send_message(kek, "Apni ma ko ja choos")
        await bot.send_message(kek, "Bhen ke laude")
        await bot.send_message(kek, "Bhen ke takke")
        await bot.send_message(kek, "Abla naari tera buble bhaari")
        await bot.send_message(kek, "Bhonsri-Waalaa")
        await bot.send_message(kek, "Bol teri gand kaise maru")
        await bot.send_message(kek, "Bur ki chatani")
        await bot.send_message(kek, "Gaand ka makhan")
        await bot.send_message(kek, "Gaand main lassan")
        await bot.send_message(kek, "Gaand main danda")
        await bot.send_message(kek, "Gaand main keera")
        await bot.send_message(kek, "Gaand mein bambu")
        await bot.send_message(kek, "Gaandfat")
        await bot.send_message(kek, "Pote kitne bhi bade ho, lund ke niche hi rehte hai")
        await bot.send_message(kek, "Hazaar lund teri gaand main")
        await bot.send_message(kek, "Jhaant ke pissu-")
        await bot.send_message(kek, "Kali Choot Ke Safaid Jhaat")
        await bot.send_message(kek, "Khotey ki aulda")
        await bot.send_message(kek, "Kutte ka awlat")
        await bot.send_message(kek, "Kutte ki jat")
        await bot.send_message(kek, "Kutte ke tatte")
        await bot.send_message(kek, "Kutte ke poot, teri maa ki choot")
        await bot.send_message(kek, "Lavde ke bal")
        await bot.send_message(kek, "muh mei lele")
        await bot.send_message(kek, "Lund Ke Pasine")
        await bot.send_message(kek, "Meri Gand Ka Khatmal")
        await bot.send_message(kek, "Moot, Mootna")
        await bot.send_message(kek, "Najayaz paidaish")
        await bot.send_message(kek, "Randi khana")
        await bot.send_message(kek, "Sadi hui gaand")
        await bot.send_message(kek, "Teri gaand main kute ka lund")
        await bot.send_message(kek, "Teri maa ka bhosda")
        await bot.send_message(kek, "Teri maa ki chut")
        await bot.send_message(kek, "Tere gaand mein keede paday")
        await bot.send_message(kek, "Ullu ke pathe")
        await bot.send_message(kek, "SUNN MADERCHOD")
        await bot.send_message(kek, "TERI MAA KA BHOSDA")
        await bot.send_message(kek, "BEHEN K LUND")
        await bot.send_message(kek, "TERI MAA KA DUD")
        await bot.send_message(kek, "MERA LAWDA LELE TU AGAR CHAIYE TOH")
        await bot.send_message(kek, "GAANDU")
        await bot.send_message(kek, "CHUTIYA")
        await bot.send_message(kek, "TERI MAA KI CHUT PE JCB CHADHAA DUNGA")
        await bot.send_message(kek, "SAMJHAA LAWDE")
        await bot.send_message(kek, "YA DU TERE GAAND ME TAPAA TAP")
        await bot.send_message(kek, "TERI BEHEN MERA ROZ LETI HAI")
        await bot.send_message(kek, "TERI GF K SAATH MMS BANAA CHUKA HU")
        await bot.send_message(kek, "TU CHUTIYA TERA KHANDAAN CHUTIYA")
        await bot.send_message(kek, "Madarchod Randi ke bacche Oye bosdike madarchod bhen ke lode tere gand me lohe ka danda garam karke dalu randwe tujhetho gali ke kutte gand pe chut rakh ke katenge me bata raha hu tere lode pe madhu makkhi Katelode ke ando pe Road roller chale tu kab bathroom me muthne Jaye tho Tera loda ghir Jaye fir tere ando me se lizard ke bacche nikle teko kidnap Kare aur childporn banaye maa ke chuttad ke lode tere saat Johnny sins rape Kare aur jab wo teko anal de tab loda andar fas Jaye bkl tere jhaat pe waxing karunga me dhek lio fir jab tu chillayega na tab tere muh me Mai gai ka gobar dalunga sale tere gand ke balo pe tel laga ke jala du me teko Anaconda leke gand me dalu tho muh se nikle maa ke lode hamesha chutiyo jaisa bartav kartha he tu maa ke Dai chawal drugs tere gand Me dalunga thi tatti nahi nikle maa darchod kabhi teko Marne ka mouka mil gaya na tho bas I'll do my best to get that tatti outof you aur tere jaise chutio ko is duniya me jagaha bhi nahi maa ke lode bandarchod tere gand me chitiya Kate wo bhi bullet ants maadarchod samj nahi aaraha tere baap NE teko kya khake paida kiya Tha kesa chutiya he tu rand ke bacche teko shadi me khana khane na mile teko gand pe 4 thappad mare sab log aur blade se likhe I want anal madarchod bosdike maccharki tatte ke baal chutiye maa ke chut pe ghode ka Lund tere gand me jaltha hu koila Dale bhen ke lode MAA KI CHUT MAI TALWAR DUNGA BC CHUT FAT JAEGI AUR USME SE ITNA KHOON NIKLEGA MZA AJAEGA DEKHNE KA SALE MAA KE BHOSDE SE BAHR AJA FIR BAAP SE ZUBAN DA TERI MAA KI CHUT CHOD CHOD KE BHOSDABNADU MADARCHOD AUR USKE UPAR CENENT LAGADU KI TERE JESA GANDU INSAAN KABHI BAHR NA A SKE ESI GANDI CHUT MAI SE LODA LASUN MADRCHOD TERI MAA KI CHUT GASTI AMA KA CHUTIA BACHA TERI MAA KO CHOD CHOD K PAGAL KAR DUNGA MAA K LODY KISI SASTIII RANDII K BACHY TERI MAA KI CHOOT MAIN TEER MAARUN GANDU HARAMI TERI COLLEGE JATI BAJI KA ROAD PEY RAPE KARONGANDU KI OLAAD HARAM KI NASAL PAPA HUN TERA BHEN PESH KAR AB PAPA KO TERI MAA KKALE KUSS MAIN KISI!")
        await bot.send_message(kek, "AUR KITNA BOLU BEY MANN BHAR GAYA MERA")
        await bot.send_message(kek, "Ab nikal ja jaake chkko k saath hilaa")
        
        CmdHelp("raid").add_command(
  "raid", "Spam User/Group With Many Bad Words"
).add_info(
  "Bad Words Raid"
).add_warning(
  "✅ Spammer/Fighter Module."
).add()

        
